---
env:
  global:
    - CC_TEST_REPORTER_ID=726714815d0585061fe1d559efdda27da342136aa38d4778d3476b337851b18d

language: node_js
node_js:
  - 12.10.0

before_script:
  - make build
  - npm install --save-dev codeclimate-test-reporter

script:
  - make test
  - make lint

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
