---
env:
  global:
    - CC_TEST_REPORTER_ID=726714815d0585061fe1d559efdda27da342136aa38d4778d3476b337851b18d

language: node_js
node_js:
  - 12.10.0

before_script:
  - make build
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +rwx ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make test
  - make lint

after_script:
  - /home/travis/build/upokusaev/frontend-project-lvl2/cc-test-reported format-coverage -o coverage/codeclimate.json
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - /home/travis/build/upokusaev/frontend-project-lvl2/cc-test-reporter upload-coverage
  - cd /home/travis/build/upokusaev/frontend-project-lvl2/
  - ls -al
